all: fit_sed fit_sed_opencl

fit_sed:
	g++ -Wall -O3 -fsingle-precision-constant -o fit_sed fit_sed_skynet.cpp

fit_sed_opencl:
	g++ -Wall -O3 -fsingle-precision-constant -DUSE_OPENCL -I. -o fit_sed_opencl fit_sed_skynet.cpp -framework OpenCL

clean:
	rm -f fit_sed
	rm -f fit_sed_opencl
